### ISSUE TITLE
Dates seems to be parsed incorrectly

### ISSUE THREAD

**Issue by PatrickvL** [guivanrv/cxbx-reloaded-compatibility-list#4]
Dates never show a day number above 12, so there's probably a parsing error somewhere

**Comment by guivanrv** [comment]
The code for date formatting was wrong from the beginning, i didn't put much thought into it when submitting initially. Now a propper parser/formatter is used - it should be fine https://github.com/guivanrv/cxbx-reloaded-compatibility-list/commit/75aade818aec73f96b89340ea67ab97a7d3b0d20
