### ISSUE TITLE
Date sorting is wrong

### ISSUE THREAD

**Issue by PatrickvL** [guivanrv/cxbx-reloaded-compatibility-list#5]
First of all, dates are shown as day-month-year (or perhaps month-day-year, can't tell due to #4 ).

This might be related to what happens when sorting the date field, here a random few samples :

1-1-2018
1-8-2017
2-12-2017
3-1-2017
7-11-2017

This is clearly wrong. I'd rather see this (assuming descending order) :

2018-1-1
2017-12-2
2017-11-7
2017-8-1
2017-3-1

**Comment by guivanrv** [comment]
https://github.com/guivanrv/cxbx-reloaded-compatibility-list/commit/75aade818aec73f96b89340ea67ab97a7d3b0d20 this should fix it. Moment.js is cool but the library I've chosen for list rendering - oh, not that smooth. I already consider redoing it again with something else :D
